-- Drop problematic enum types (safe to run)
DROP TYPE IF EXISTS public.enum_documents_mime_type;
DROP TYPE IF EXISTS public.enum_videos_mime_type;
DROP TYPE IF EXISTS public.enum_audios_mime_type;

-- Drop any leftover autogenerated duplicate index names that block sync
DROP INDEX IF EXISTS "xapi_statements_";

-- Create explicit expression indexes for xapi_statements with fixed names
-- (run AFTER confirming table exists and no conflicting index names remain)
CREATE INDEX IF NOT EXISTS idx_xapi_actor_userid ON xapi_statements (((actor->>'userId')::uuid));
CREATE INDEX IF NOT EXISTS idx_xapi_object_objectid ON xapi_statements (((object->>'objectId')::uuid));

-- Optional: verify enums
-- SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value
-- FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
-- WHERE n.nspname = 'public' AND t.typname IN ('enum_documents_mime_type','enum_videos_mime_type','enum_audios_mime_type')
-- GROUP BY 1;
